org: ashley7kelly
app: strkr
service: strkr
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: scripts/handler.hello
    events:
      - httpApi:
          path: /
          method: get
