org: ashley7kelly
app: strkr
service: strkr
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
      - Effect: Allow
        Action:
          - rds-data:ExecuteSql
          - rds-data:ExecuteStatement
        Resource: "arn:aws:rds:us-east-1:279499514840:cluster:stkr-1"
      - Effect: Allow
        Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:PutResourcePolicy
          - secretsmanager:PutSecretValue
          - secretsmanager:DeleteSecret
          - secretsmanager:DescribeSecret
          - secretsmanager:TagResource
        Resource: "arn:aws:secretsmanager:us-east-1:279499514840:secret:strk-access-LZpcd5"

functions:
  new-streak:
    handler: scripts/streaks.addStreak
    events:
      - http:
          path: /new-streak
          method: post

  get-streak-by-id:
    handler: scripts/streaks.getStreakByID
    events:
      - http:
          path: /get-streak-by-id/{id}
          method: get
  
  get-streak-by-user:
    handler: scripts/streaks.getStreakByUser
    events:
      - http:
          path: /get-streak-by-user/{id}
          method: get

  increment-streak:
    handler: scripts/streaks.incrementStreak
    events:
      - http:
          path: /increment-streak
          method: post
