org: ashley7kelly
app: strkr
service: strkr
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  new-streak:
    handler: scripts/streaks.addStreak
    events:
      - http:
          path: /new-streak
          method: post

  get-streak-by-id:
    handler: scripts/streaks.getStreakByID
    events:
      - http:
          path: /get-streak-by-id/{id}
          method: get
  
  get-streak-by-user:
    handler: scripts/streaks.getStreakByUser
    events:
      - http:
          path: /get-streak-by-user/{id}
          method: get

  increment-streak:
    handler: scripts/streaks.incrementStreak
    events:
      - http:
          path: /increment-streak
          method: post
